### ISSUE TITLE
strange behavior when `set selection=exclusive`

### ISSUE THREAD

**Issue by ZSaberLv0** [garbas/vim-snipmate#285] opened 2022-01-11 15:46 UTC
min config:

``` vim
filetype plugin indent on
syntax on
set nocompatible
let g:plug_home = $HOME . '/.vim/bundle'
let g:plug_url_format = 'https://github.com/%s'
execute 'source ' . g:plug_home . '/vim-plug/plug.vim'
silent! call plug#begin()
Plug 'junegunn/vim-plug'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets'
let g:snipMate = {
            \   'snippet_version' : 1,
            \   'override' : 1,
            \   'always_choose_first' : 1,
            \   'no_match_completion_feedkeys_chars' : '',
            \ }
call plug#end()

set selection=exclusive
```

to reproduce:
1. `vim -u min.vim`, the main code is `set selection=exclusive`
1. trigger any snippet, for example
    1. `set ft=vim`
    1. input `f` and `<tab>` to trigger the snippet
1. continue to use `<tab>` to jump next marker, the issue occur: the first one or more marker can jump properly, but later ones can not

**Comment by ajzafar** [comment] 2023-03-10 18:53
@ZSaberLv0 I'm sorry, but I'm not able to reproduce this, both on my own setup and with that minimal vimrc you provided. Can you maybe also share a sample snippet you're having trouble with?

**Comment by ZSaberLv0** [comment] 2023-03-11 14:40
oh, the minimal vimrc should have the plugins installed under `g:plug_home`

the sample snippet is just the `honza/vim-snippets`, in the reproduce steps, input `f` and `<tab>` would trigger "function" expand of `vim` filetype: https://github.com/honza/vim-snippets/blob/master/snippets/vim.snippets#L11

---

here is a reproduce screenshot
(I do not have proper screenshot software, the gif frame time is not real world time, sorry about that)

![a](https://user-images.githubusercontent.com/6846867/224490685-d072ad46-3d69-44d3-949c-f1ae51295d0c.gif)

1. the first snip expand (with `set selection=exclusive`), get stuck in the first line and can not jump to next line, even keep pressing `<tab>`
2. the second snip expand (with `set selection=inclusive`), can jump to next line by keep pressing `<tab>`, this is expected behavior, since the original snippets has the `${0}` in the next line: https://github.com/honza/vim-snippets/blob/master/snippets/vim.snippets#L13

**Comment by ajzafar** [comment] 2023-03-12 22:22
@ZSaberLv0 I just pushed a fix. I'm not sure this covers all edge cases, so please reopen this if any more issues arise.

Thank you!

**Closed** 2023-03-12 22:22 UTC
