### ISSUE TITLE
snipMateBack mapping not working

### ISSUE THREAD

**Issue by chechoRP** [garbas/vim-snipmate#189] opened 2015-02-10 17:44 UTC
Hello. I am trying to customize the snipMateBack mapping by following the documentation guidelines. Here's what I have in my .vimrc
```
:imap <leader>t <Plug>snipMateBack
:smap <leader>t <Plug>snipMateBack
```
However when I try such mapping it does not do anything and I can only go to previous location with the default <S-Tab>

Interestingly, if I do the same mapping but with other actions such as `<Plug>snipMateShow` or `<Plug>snipMateTrigger`  my customized mapping does work. So the issue is specifically with the `snipMateBack` action.   

*Note:* The reason why I need to do this is because I installed **delimitMate** which also has `<S-Tab>` mapped to a function that exits a matching pair. 

Thanks.

**Comment by ajzafar** [comment] 2015-02-10 21:06
@chechoRP Hmm I am unable to reproduce this. What are you using as your map leader?

> However when I try such mapping it does not do anything and I can only go to previous location with the default

Hmm if your map is being created correctly, then SnipMate shouldn't be mapping the default at all. At least it doesn't for me when I try putting your mappings in my `.vimrc`. Can you also check that you're using an up-to-date clone of master?

**Comment by chechoRP** [comment] 2015-02-10 23:15
@ajzafar My map leader is **,** . I don't remember which clone of master did I get. I will check that out. On the meantime I remapped `<S-Tab>` from delimitMate and it is working fine.

**Comment by ajzafar** [comment] 2015-02-23 20:24
@chechoRP I just meant pull from master to make sure you're up to date. Is the problem fixed now?

**Comment by chechoRP** [comment] 2015-02-23 20:27
@ajzafar I did that and now is working fine. Thanks!

**Comment by ajzafar** [comment] 2015-02-23 20:39
Great!

**Closed by ajzafar** 2015-02-23 20:39 UTC
