### ISSUE TITLE
Snipmate very slow on tab press

### ISSUE THREAD

**Issue by patforg** [garbas/vim-snipmate#195] opened 2015-03-07 04:22 UTC
Hi,

Snipmate caused my tab completion to become very slow.

When I try to use omnicomplete (which is also bound to the tab key) it takes about 10 seconds before I get suggestions. 

When I disable snipmate all goes back to normal.  Would love to provide more info, not sure what else can help.

Any ideas?

**Comment by ajzafar** [comment] 2015-03-07 18:38
Can you share the following information to start with, @patforg?

- What is your Vim version (including the patch level)?
- Are you using SuperTab? If not, how are you combining SnipMate and omnicompletion to the same key?
- Please make sure you're on master.
- Does this happen every time you press tab without an existing trigger or only after certain characters? See #156 for example.
- Are you on Windows? Again see #156.

**Comment by patforg** [comment] 2015-03-07 20:23
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled May  4 2012 04:21:49)
Included patches: 1-429
Modified by pkg-vim-maintainers@lists.alioth.debian.org

Plugins I have 
```code
bufkill.vim
ctrlp.vim
molokai
nerdtree
phpcomplete.vim
php.vim
supertab
tlib_vim
vim-addon-mw-utils
vim-javascript
vim-move
vim-node
vim-snipmate
vim-surround
vundle
xoria256.vim
```
yes on master for snipmate
when I do git branch -v
```code
* master 4b8232f Merge branch 'vundle_plugin_syntax' of https://github.com/mikeastock/vim-snipmate
```
On Ubuntu 
Linux maggie 3.5.0-23-generic #35~precise1-Ubuntu SMP Fri Jan 25 17:13:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

My test file:

```php
<?php

$test = true;
$noTest  = false;

```

The problem happens when I write $te<tab>  or $noTe<tab>  (or any other completion)

**Comment by ajzafar** [comment] 2015-03-10 01:32
It turns out this is caused by a bug in Vim, fixed in 7.3.1295. I just pushed a workaround. Let me know how it works.

**Comment by patforg** [comment] 2015-03-10 20:47
Did an update,  now working with no lag, thanks for the quick fix!

You save me from going crazy.  Cheers

**Comment by ajzafar** [comment] 2015-03-11 17:15
Glad to hear it!

**Closed by ajzafar** 2015-03-11 17:15 UTC
