### ISSUE TITLE
Custom mapping of triggers 

### ISSUE THREAD

**Issue by Atulkmr** [garbas/vim-snipmate#251] opened 2017-04-03 17:23 UTC
So I have read through a lot of posts by now and none of them seemed to reach a conclusive end.

I want to use YouCompleteMe plugin which also uses tab key as a trigger.
 
I have tried adding these to .vimrc but nothing seemed to change
`imap <C-J> <Plug>snipMateNextOrTrigger`
 `smap <C-J> <Plug>snipMateNextOrTrigger`

Also, I don't understand what are the assigned values for different keys. 
Like C == Ctrl and S == Shift. Where can I find the list for other keys ?

**Comment by Atulkmr** [comment] 2017-04-05 16:59
I gave up and turned towards UltiSnips finally.
No issues remapping trigger keys there and moreover it readily links to the YCM completion engine.

**Comment by ajzafar** [comment] 2017-04-20 09:20
I'm afraid I'm unable to reproduce this. The exact maps you provided work as I expect: `<C-J>` expands snippets and jumps between stops. That notation is what Vim uses. The docs on it can be found in the help at `:h key-notation`. Sorry to have lost you. If you're no longer using SnipMate though and I can't reproduce this, I'm going to go ahead and close it.

**Closed by ajzafar** 2017-04-20 09:20 UTC
