### ISSUE TITLE
Trigger '...' not expanding

### ISSUE THREAD

**Issue by benhamill** [garbas/vim-snipmate#180] opened 2015-01-22 06:07 UTC
I was hoping to make the following snippet (for use in, like, Markdown files or plaintext, etc.):

```
snippet ...
    …
```

However, when I type `...<tab>` it doesn't expand (and does a tab). I have another snippet in the same file that replaces `--` with `—` and it's working fine, so I know the file's in scope.

Am I doing something wrong, here? Or maybe dots are just a problem all around? Seeing #65 made me think that my snippet should work, but also makes me doubt its wisdom.

Halp?

**Comment by benhamill** [comment] 2015-01-22 06:10
Aaaaand, because I just posted this, I figured it out:

I want to be able to type `To be continued...<tab>` and have it swap the periods for the ellipsis. But the fact that there's no leading whitespace is making SnipMate confused. This is true of both the ellipsis and emdash snippets I made.

Am I SOL on these because of that?

**Comment by ajzafar** [comment] 2015-01-24 02:56
@benhamill I just pushed what should be a fix for this. Let me know how it works.

**Comment by ajzafar** [comment] 2015-03-01 19:45
Closing this due to inactivy and irreproducibility. The issue should have been fixed in 0e46029.

**Closed by ajzafar** 2015-03-01 19:45 UTC
