### ISSUE TITLE
subdirectory filetype snippets aren't read

### ISSUE THREAD

**Issue by elig0n** [garbas/vim-snipmate#286] opened 2022-01-21 02:43 UTC
A snippets directory which is listed in my `rtp` holds the file `.../snippets/javascript/javascript.snippets` (from [honza/vim-snippets](https://www.github.com/honza/vim-snippets)) but it isn't loaded for a matching filetype (`:SnipMateOpenSnippetsFiles` does not list the file). 

Other top level files are loaded succesfully, i.e.: `.../snippets/other.snippets`. 

Temporarily I linked to my desired nested .snippets file in its parent directory and so the file is loaded successfully.

All files and directories have the required permissions and ownership to read them.

_Linux, VIM 8.2, latest git vim-snipmate (via plugged)_

**Comment by ajzafar** [comment] 2022-01-23 01:41
Something's not right here, because `other.js` won't be checked for snippets, regardless of where it's located. What are the actual filenames of your snippet files? They should follow one of the following templates (taken directly from the documentation):

    .../snippets/<scope>.snippets
    .../snippets/<scope>_<name>.snippets
    .../snippets/<scope>/<name>.snippets
    .../snippets/<scope>/<trigger>.snippet
    .../snippets/<scope>/<trigger>/<description>.snippet

where `<scope>` is the filetype or syntax you want to use (probably `javascript` for you), `<name>` is an arbitrary name that SnipMate doesn't actually use, `<trigger>` is your trigger if you want to use a single snippet per file, and `<description>` is a description for the trigger that can be used to differentiate it for multisnip (`:h SnipMate-multisnip`) purposes.

**Comment by elig0n** [comment] 2022-01-24 07:52
@ajzafar hey, I actually meant `other.snippets` and `javascript.snippets`. The snippets are from package [vim-snippets](https://www.github.com/honza/vim-snippets).  `vim-snippets/snippets/javascript/javascript.snippets` and `vim-snippets/snippets/coffee/coffee.snippets` aren't loaded automatically (or manually) for their matching filetype except when I link their sub-directories with a matching .snippets link.

**Comment by elig0n** [comment] 2022-01-24 07:53
@ajzafar hey, I actually meant `other.snippets` and `javascript.snippets`. The snippets are from package [vim-snippets](https://www.github.com/honza/vim-snippets).  `vim-snippets/snippets/javascript/javascript.snippets` and `vim-snippets/snippets/coffee/coffee.snippets` aren't loaded automatically (or manually) for their matching filetype.

**Comment by ajzafar** [comment] 2022-01-26 04:17
@elig0n I am way busier right now than I anticipated, but I can confirm that the files are loaded as documented on my end. When I get some time I'll experiment a little to try and figure out what's different on your end, but until then if you are able to play with it, please do so and keep this issue updated. A good place to start would be to try and create a minimal vimrc that recreates the issue.

**Comment by ajzafar** [comment] 2024-01-01 19:07
@elig0n I am going to close this. From rereading the issue right now, it seems there's a misunderstanding on how files should be named for SnipMate to recognize them. If there's still confusion, please feel free to reopen this as I'd be happy to help you sort it out.

**Closed by ajzafar** 2024-01-01 19:07 UTC
