### ISSUE TITLE
Unknown function: snipMate#TriggerSnippet

### ISSUE THREAD

**Issue by code4pay** [garbas/vim-snipmate#269] opened 2018-08-01 07:00 UTC
if I type my snippet character and hit tab I get 

```
E117: Unknown function: snipMate#TriggerSnippet
E15: Invalid expression: snipMate#TriggerSnippet()
```
using vim 8,   plugin loaded by vundle
I have commented out every command in my vimrc  and deleted all other plugins except for loading this plugin and get the same error.

Thanks in advance for anyhelp

**Comment by ajzafar** [comment] 2018-08-17 23:58
@code4pay Are you using master from GitHub? Please make sure that you are.

**Comment by ajzafar** [comment] 2018-08-18 10:32
@code4pay Are you on Windows? If so this could be a duplicate of #264

**Comment by code4pay** [comment] 2018-08-20 02:44
this is the vundle  packages section of my vimrc

**Comment by code4pay** [comment] 2018-08-20 02:45
Hi Thanks for the reply,  No Not on Windows on Debian Wheezy ,   and using Vundle checked status of branch and did a pull but it is uptodate with master. 
Vundle section of my vimrc
```
 set nocompatible                                                     
 filetype off                                                         
                                                                      
 set rtp+=~/.vim/bundle/Vundle.vim                                    
 call vundle#begin()                                                  
                                                                      
 Plugin 'VundleVim/Vundle.vim'                                        
                                                                      
 "vundle managed packages                                             
 Plugin 'mileszs/ack.vim'                                             
 Plugin 'tpope/vim-fugitive'                                          
 Plugin 'w0rp/ale'                                                    
 Plugin 'ctrlpvim/ctrlp.vim'                                          
 Plugin 'ap/vim-buftabline'                                           
 Plugin 'MarcWeber/vim-addon-mw-utils'                                
 Plugin 'tomtom/tlib_vim'                                             
 Plugin 'garbas/vim-snipmate'                                         
 call vundle#end()                                                    
```

**Comment by code4pay** [comment] 2018-08-20 02:46
Note I have tried both file type on and off with no change.

**Comment by ajzafar** [comment] 2018-09-02 21:17
@code4pay Can you provide a minimal vimrc that produces this issue for you? That is a vimrc that contains absolutely nothing but what's necessary to produce this issue. Take out extraneous plugins, extraneous settings, and so on.

**Comment by code4pay** [comment] 2018-09-03 09:18
Thanks @ajzafar, I worked it out when I went to start cleaning out my vimrc.   I always work in the same saved session file which must have had some thing set that broke the plugin even when I reloaded my vimrc.   When I went to edit the vimrc without first loading the  session file it worked.   Apologies for not picking that up earlier.
thanks for your help.

**Comment by ajzafar** [comment] 2018-09-03 14:40
Glad to help.

**Closed by ajzafar** 2018-09-03 14:40 UTC
